package proyecto.unodev;
import javax.swing.JButton;
import javax.swing.JPanel;
import java.awt.Color;

public class FrmPrincipal extends javax.swing.JFrame {
    int indButtonSel = 1;
    
    public FrmPrincipal() {
        initComponents();
        btnInicioMouseClicked(null);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pMenu = new javax.swing.JPanel();
        btnInicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAcerca = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        pCalcular = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblDescripcionCalculo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCantidadInicialBacterias = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTiempoEspera = new javax.swing.JTextField();
        btnRealizarCalculo = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultados = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbxBacteria = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        txtTiempoEspera1 = new javax.swing.JTextField();
        pInicio = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pAcerca = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(860, 460));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pMenu.setBackground(new java.awt.Color(46, 58, 74));

        btnInicio.setBackground(new java.awt.Color(67, 83, 108));
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInicioMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INICIO");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/home.png"))); // NOI18N

        javax.swing.GroupLayout btnInicioLayout = new javax.swing.GroupLayout(btnInicio);
        btnInicio.setLayout(btnInicioLayout);
        btnInicioLayout.setHorizontalGroup(
            btnInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnInicioLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnInicioLayout.setVerticalGroup(
            btnInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnInicioLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(btnInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addGap(16, 16, 16))
        );

        btnCalcular.setBackground(new java.awt.Color(147, 186, 35));
        btnCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalcularMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCalcularMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCalcularMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CALCULAR");
        jLabel2.setAlignmentX(0.5F);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/calc.png"))); // NOI18N

        javax.swing.GroupLayout btnCalcularLayout = new javax.swing.GroupLayout(btnCalcular);
        btnCalcular.setLayout(btnCalcularLayout);
        btnCalcularLayout.setHorizontalGroup(
            btnCalcularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCalcularLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        btnCalcularLayout.setVerticalGroup(
            btnCalcularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCalcularLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(btnCalcularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addGap(17, 17, 17))
        );

        btnAcerca.setBackground(new java.awt.Color(67, 83, 108));
        btnAcerca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAcerca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAcercaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAcercaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAcercaMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("INFORMACIÓN");
        jLabel3.setAlignmentX(0.5F);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/about.png"))); // NOI18N

        javax.swing.GroupLayout btnAcercaLayout = new javax.swing.GroupLayout(btnAcerca);
        btnAcerca.setLayout(btnAcercaLayout);
        btnAcercaLayout.setHorizontalGroup(
            btnAcercaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAcercaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAcercaLayout.setVerticalGroup(
            btnAcercaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAcercaLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(btnAcercaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addGap(17, 17, 17))
        );

        lblLogo.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(255, 255, 255));
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/logo.png"))); // NOI18N

        javax.swing.GroupLayout pMenuLayout = new javax.swing.GroupLayout(pMenu);
        pMenu.setLayout(pMenuLayout);
        pMenuLayout.setHorizontalGroup(
            pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCalcular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAcerca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pMenuLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pMenuLayout.setVerticalGroup(
            pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblLogo)
                .addGap(55, 55, 55)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(btnAcerca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        getContentPane().add(pMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 460));

        pCalcular.setBackground(new java.awt.Color(227, 227, 225));
        pCalcular.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(66, 83, 109));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDescripcionCalculo.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblDescripcionCalculo.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcionCalculo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDescripcionCalculo.setText("<html> <b>IMPORTANTE:</b> <p>Los resultados obtenidos del cálculo son las cantidades de UFC, de la bacteria seleccionada, en cada intervalo de tiempo transcurrido. El tiempo óptimo de fermentación está indicado.</p></html>");
        jPanel3.add(lblDescripcionCalculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 11, 650, 60));

        pCalcular.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 80));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(97, 93, 124));
        jLabel7.setText("INGRESO DE DATOS");
        pCalcular.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 109, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(97, 93, 124));
        jLabel8.setText("Cantidad Inicial de bacterias");
        pCalcular.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 205, -1));

        txtCantidadInicialBacterias.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtCantidadInicialBacterias.setForeground(new java.awt.Color(97, 93, 124));
        txtCantidadInicialBacterias.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCantidadInicialBacterias.setText("1000");
        txtCantidadInicialBacterias.setPreferredSize(new java.awt.Dimension(42, 30));
        pCalcular.add(txtCantidadInicialBacterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 240, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(97, 93, 124));
        jLabel9.setText("Tiempo de espera de crecimiento");
        pCalcular.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 210, -1));

        txtTiempoEspera.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtTiempoEspera.setForeground(new java.awt.Color(97, 93, 124));
        txtTiempoEspera.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTiempoEspera.setText("72");
        pCalcular.add(txtTiempoEspera, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 240, 30));

        btnRealizarCalculo.setBackground(new java.awt.Color(241, 241, 241));
        btnRealizarCalculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(97, 93, 124));
        jLabel10.setText("Calcular");

        javax.swing.GroupLayout btnRealizarCalculoLayout = new javax.swing.GroupLayout(btnRealizarCalculo);
        btnRealizarCalculo.setLayout(btnRealizarCalculoLayout);
        btnRealizarCalculoLayout.setHorizontalGroup(
            btnRealizarCalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRealizarCalculoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel10)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        btnRealizarCalculoLayout.setVerticalGroup(
            btnRealizarCalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRealizarCalculoLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pCalcular.add(btnRealizarCalculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 408, -1, 30));

        jPanel8.setBackground(new java.awt.Color(214, 217, 223));

        tblResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tiempo Transcurrido", "Cantidad UFC"
            }
        ));
        tblResultados.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(tblResultados);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(97, 93, 124));
        jLabel14.setText("RESULTADOS");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel14)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pCalcular.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 390, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(97, 93, 124));
        jLabel13.setText("Nombre de la bacteria");
        pCalcular.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 147, 205, -1));

        cbxBacteria.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        cbxBacteria.setForeground(new java.awt.Color(97, 93, 124));
        cbxBacteria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Streptococcus Thermophilus", "Leuconostoc Bulgaricus", "Streptococcus Lactis", "Leuconostoc Cremoris", "Streptococcus Diacetylactis", "Penicillium Camemberti", "Penicillium Glaucum", "Penicillium Roqueforti", "Lactobacillus Acidophilus" }));
        pCalcular.add(cbxBacteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 171, 240, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(97, 93, 124));
        jLabel19.setText("Cantidad de la solución");
        pCalcular.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 210, -1));

        txtTiempoEspera1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtTiempoEspera1.setForeground(new java.awt.Color(97, 93, 124));
        txtTiempoEspera1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTiempoEspera1.setText("500");
        pCalcular.add(txtTiempoEspera1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 240, 30));

        getContentPane().add(pCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 700, 460));

        pInicio.setBackground(new java.awt.Color(227, 227, 225));
        pInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/microorganismo.png"))); // NOI18N
        pInicio.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, -1, 230));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(97, 93, 124));
        jLabel15.setText("Bienvenidos");
        pInicio.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 410, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(97, 93, 124));
        jLabel16.setText("<html> Pasteur Labs es un aplicativo que permite calcular el pronóstico de crecimiento poblacional microbiano. Con sólo el ingreso de unos pocos datos se obtienen los resultados. </html>");
        pInicio.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 610, 70));

        getContentPane().add(pInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 700, 460));

        pAcerca.setBackground(new java.awt.Color(227, 227, 225));
        pAcerca.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/microorganismo.png"))); // NOI18N
        pAcerca.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, -1, 230));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(97, 93, 124));
        jLabel17.setText("Información de ayuda para el cálculo");
        pAcerca.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 410, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(97, 93, 124));
        jLabel18.setText("<html>\n<p>Las unidades de medias de cada dato de entrada son las siguientes:</p>\n<ul style=\"list-style-type:square\">\n<li> <b>Cantidad inicial de bacterias:</b> UFC (Unidades Formadoras de Colonias)</li>\n<li> <b>Tiempo de espera de crecimiento:</b> Horas</li>\n<li> <b>Cantidad de la solución:</b> mL (mililitros)</li>\n</ul>  \n<p>Las bacterias utilizadas para la fermentación de algunos de los productos lácteos son:</p>\n<ul style=\"list-style-type:square\">\n<li> <b>Yogurt Natural/Griego</b> (Streptococcus Thermophilus, Leuconostoc Bulgaricus)</li>\n<li> <b>Yogurt Probiótico</b> (Streptococcus Thermophilus, Leuconostoc Bulgaricus)</li>\n<li> <b>Queso Provolone</b> (Streptococcus Thermophilus, Leuconostoc Bulgaricus)</li>\n<li> <b>Queso Romano</b> (Streptococcus Thermophilus, Leuconostoc Bulgaricus)</li>\n<li> <b>Queso Paria</b> (Streptococcus Thermophilus, Leuconostoc Bulgaricus)</li>\n<li> <b>Queso Gouda</b> (Streptococcus Lactis, Leuconostoc Cremoris, Streptococcus Diacetylactis)</li>\n<li> <b>Queso Cheddar</b> (Streptococcus Lactis, Leuconostoc Cremoris, Streptococcus Diacetylactis)</li>\n<li> <b>Queso Fresco</b> (Streptococcus Lactis, Leuconostoc Cremoris, Streptococcus Diacetylactis)</li>\n<li> <b>Queso Carmembert</b> (Penicillium Camemberti)</li>\n<li> <b>Queso Brie</b> (Penicillium Camemberti)</li>\n<li> <b>Queso Gorgonzola</b> (Penicillium Glaucum)</li>\n<li> <b>Queso Roquefort</b> (Penicillium Roqueforti)</li>\n<li> <b>Queso Danish Blue</b> (Penicillium Roqueforti)</li>\n</ul>  \n</html>");
        jLabel18.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pAcerca.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 610, 340));

        getContentPane().add(pAcerca, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 700, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseEntered
        setDefaultButtonColor_Hover(1);
    }//GEN-LAST:event_btnInicioMouseEntered

    private void btnCalcularMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcularMouseEntered
        setDefaultButtonColor_Hover(2);
    }//GEN-LAST:event_btnCalcularMouseEntered

    private void btnAcercaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcercaMouseEntered
        setDefaultButtonColor_Hover(3);
    }//GEN-LAST:event_btnAcercaMouseEntered

    private void btnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseClicked
        indButtonSel = 1;
        setDefaultButtonColor_Click(indButtonSel);
        selectPanel();
    }//GEN-LAST:event_btnInicioMouseClicked

    private void btnCalcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcularMouseClicked
        indButtonSel = 2;
        setDefaultButtonColor_Click(indButtonSel);
        selectPanel();
    }//GEN-LAST:event_btnCalcularMouseClicked

    private void btnAcercaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcercaMouseClicked
        indButtonSel = 3;
        setDefaultButtonColor_Click(indButtonSel);
        selectPanel();
    }//GEN-LAST:event_btnAcercaMouseClicked

    private void btnInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseExited
        setDefaultButtonColor_Leave();
    }//GEN-LAST:event_btnInicioMouseExited

    private void btnCalcularMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcularMouseExited
        setDefaultButtonColor_Leave();
    }//GEN-LAST:event_btnCalcularMouseExited

    private void btnAcercaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcercaMouseExited
        setDefaultButtonColor_Leave();
    }//GEN-LAST:event_btnAcercaMouseExited
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }
    
    private void setDefaultButtonColor_Hover(int indButtonFocused){
        loop1: for (int i = 1; i <= 3; i++) {
            JPanel button = getButtonByIndex(i);
            if (i == indButtonSel) continue;
            if (i != indButtonFocused)
                onMouseLeave(button);
            else
                onMouseHover(button);
        }
    }
    
    private void setDefaultButtonColor_Leave(){
        for (int i = 1; i <= 3; i++) {
            JPanel button = getButtonByIndex(i);
            if (i != indButtonSel)
                onMouseLeave(button);
        }
    }
    
    private void setDefaultButtonColor_Click(int indButtonClicked){
        for (int i = 1; i <= 3; i++) {
            JPanel button = getButtonByIndex(i);
            if (i != indButtonClicked)
                onMouseLeave(button);
            else
                onMouseClick(button);
        }
    }
    
    private JPanel getButtonByIndex(int indice){
        switch (indice)
        {
            case 1: return btnInicio;
            case 2: return btnCalcular;
            case 3: return btnAcerca;
            default: return null;
        }
    }
    
    private void selectPanel(){
        boolean visible;
        for (int i = 1; i <= 3; i++) {
            visible = false;
            JPanel panel = getPanelByIndex(i);
            if (i == indButtonSel)
                visible = true;
            panel.setVisible(visible);
        }
    }
    
    private JPanel getPanelByIndex(int indice){
        switch (indice)
        {
            case 1: return pInicio;
            case 2: return pCalcular;
            case 3: return pAcerca;
            default: return null;
        }
    }
    
    //<editor-fold defaultstate="collapsed" desc="User Events">
    private void onMouseHover(JPanel panel){
        panel.setBackground(new Color(178, 215, 116));
    }
    
    private void onMouseLeave(JPanel panel){
        panel.setBackground(new Color(67, 83, 108));
    }
    
    private void onMouseClick(JPanel panel){
        panel.setBackground(new Color(147, 186, 35));
    }
    //</editor-fold>
            
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAcerca;
    private javax.swing.JPanel btnCalcular;
    private javax.swing.JPanel btnInicio;
    private javax.swing.JPanel btnRealizarCalculo;
    private javax.swing.JComboBox<String> cbxBacteria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescripcionCalculo;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel pAcerca;
    private javax.swing.JPanel pCalcular;
    private javax.swing.JPanel pInicio;
    private javax.swing.JPanel pMenu;
    private javax.swing.JTable tblResultados;
    private javax.swing.JTextField txtCantidadInicialBacterias;
    private javax.swing.JTextField txtTiempoEspera;
    private javax.swing.JTextField txtTiempoEspera1;
    // End of variables declaration//GEN-END:variables
}
